# Generated by Django 4.0.4 on 2022-05-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_innovation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=1000)),
            ],
        ),
    ]
