# Generated by Django 4.0.4 on 2022-05-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics_innovation', '0005_alter_filehandler_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehandler',
            name='filepath',
        ),
    ]
