# Generated by Django 4.0.4 on 2022-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_innovation', '0007_filehandler_filepath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileTracker',
        ),
        migrations.AlterField(
            model_name='filehandler',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
