# Generated by Django 4.0.4 on 2022-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics_innovation', '0008_delete_filetracker_alter_filehandler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehandler',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
